# SPDX-License-Identifier: Apache-2.0

CC = /opt/local/bin/clang
LIBDIR = /opt/local/libexec/llvm-17/lib
INCDIR = /opt/local/libexec/llvm-17/include

all:
	$(CC) -g -L $(LIBDIR) -lclang -I $(INCDIR) -rpath $(LIBDIR) source/ffigen5.c -o ffigen5

